### ISSUE TITLE
Fix build on all platforms

### ISSUE THREAD

**Issue by avive** [spacemeshos/ledger-sdk#7]
Update the project to be buildable on ubuntu, windows 10 and macOS (Intel and M1)

# macOS build issues
- M1 cpu
- Xcode CL tools v2384 (Xcode 12.5)
- Node v14.16.1
- Yarn v1.22.5
- Npm v6.14.12

make fails with ngyp error.
Project should be buildable on macOS

# Ubuntu and Windows 10
Please verify project is buildable

**Comment by AndrewAR2** [comment]
Fixed for macOS and Windows.
